apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-testapp-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: student-testapp
  template:
    metadata:
      labels:
        app: student-testapp
    spec:
      containers:
      - name: student-testapp
        image: kayuze/student-testapp:latest
        ports:
        - containerPort: 5000
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
        livenessProbe:
          httpGet:
            path: /student
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /student
            port: 5000
          initialDelaySeconds: 3
          periodSeconds: 5